=== venkataramanavgit/EP-skill/Skill/WebContent/task1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Students (Student+)>
<!ELEMENT Student (name,email,marks,class)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT marks (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ATTLIST Student sid ID #REQUIRED>

=== venkataramanavgit/EP-skill/Skill/WebContent/task1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Students SYSTEM "task1.dtd">
<Students>
	<Student sid="a">
		
		<name>venkat</name>
		<email>ramanav9347@gmail.com</email>
		<marks>24</marks>
		<class>2</class>
	</Student>
	<Student sid="b">
		
		<name>ramana</name>
		<email>remiremi89@gmail.com</email>
		<marks>24</marks>
		<class>4</class>
	</Student>
	<Student sid="c">
		
		<name>suhas</name>
		<email>anav9347@gmail.com</email>
		<marks>25</marks>
		<class>5</class>
	</Student >
	<Student  sid="d">
		
		<name>manikanta</name>
		<email>manaikanatav9347@gmail.com</email>
		<marks>24</marks>
		<class>6</class>
	</Student>
	<Student sid="e">
		
		<name>pavan</name>
		<email>pavanv9347@gmail.com</email>
		<marks>23</marks>
		<class>7</class>
	</Student>
</Students>
