=== venkataramanavgit/EP-skill/Skill/WebContent/task2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Students">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Student" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" />
							<xs:element name="email" type="xs:string" />
							<xs:element name="marks" type="xs:string" />
							<xs:element name="class" type="xs:string" />

						</xs:sequence>
						<xs:attribute name="sid" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== venkataramanavgit/EP-skill/Skill/WebContent/task2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Students xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="task2.xsd">
 
	<Student sid="a">
	<name>venkat</name>
		<email>ramanav9347@gmail.com</email>
		<marks>24</marks>
		<class>2</class>
	</Student>
	<Student sid="b">
		
		<name>ramana</name>
		<email>remiremi89@gmail.com</email>
		<marks>24</marks>
		<class>4</class>
	</Student>
	<Student sid="c">
		
		<name>suhas</name>
		<email>anav9347@gmail.com</email>
		<marks>25</marks>
		<class>5</class>
	</Student >
	<Student  sid="d">
		
		<name>manikanta</name>
		<email>manaikanatav9347@gmail.com</email>
		<marks>24</marks>
		<class>6</class>
	</Student>
	<Student sid="e">
		
		<name>pavan</name>
		<email>pavanv9347@gmail.com</email>
		<marks>23</marks>
		<class>7</class>
	</Student>
</Students>
